Models/Alumno.cs
namespace ProyHerramientas.Models
{
    public class Alumno
    {
        public int Id {get;set;}
        public string Nombre {get;set;}
        public string Apellido {get;set;}
    }
}

Pages/Alumnos/Editar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations; 

namespace ProyHerramientas.Pages
{
    [BindProperties]
    public class EditarModel : PageModel
    {
        
        public int id {get;set;}
        [DataType("Password")]
        public string clave{get;set;}
        public bool recibido {get;set;}
        [DataType("EmailAddress")]
        public string mail {get;set;}
        public IFormFile archivo {get;set;}
        public void OnGet()
        {
            id=9999;
        }

        public void OnPost(){
            var numeroid=id;
            var pass=clave;
        }
    }
}

Pages/Alumnos/Nuevo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProyHerramientas.Pages.Alumnos
{
    public class NuevoModel : PageModel
    {
        public int TotalAlumnos=20;
        public string NombreProfesor {get;set;}
        public void OnGet()
        {
            ViewData["instituto"]="ISTEA"; 
            NombreProfesor="Laura Alonso";
        }
        public void OnPost(){
            NombreProfesor="Marina Lopez";
            //var formulario=Request.Form; 
            var numeroid= Request.Form["id"];
            var fecha=Request.Form["fechanacimiento"];
            var pass=Request.Form["clave"];
            var recibi=Request.Form["recibido"];
            var opcion=Request.Form["opcion"];
            var mail=Request.Form["mail"];
            var archivo=Request.Form["archivo"];
            var rango=Request.Form["rango"];

        }
        public void OnPostModificar(){
            NombreProfesor="Nicolas Fernandez";
        }

        public IActionResult OnPostVerificar(){
            return Page();
            //return RedirectToPage("Index");
        }
    }
}

Pages/Profesores/Editar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyHerramientas.Models;
using ProyHerramientas.Servicios;

namespace ProyHerramientas.Pages.Profesores
{
    public class EditarModel : PageModel
    {
        [TempData]
        public string MensajeExitoso{get;set;}
        public List<SelectListItem> MateriasLista { get; set; }
        private readonly IProfesorServicio _profService;
        private readonly IMateriaServicio _mateService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public EditarModel(IProfesorServicio profServicio,IMateriaServicio mateServicio, IWebHostEnvironment hostingEnviroment)
        {
            _profService = profServicio;
            _mateService = mateServicio;
            _hostingEnvironment = hostingEnviroment;
        }

        [BindProperty]
        public Profesor Profesor { get; set; }
        public void OnGet(int leg)
        {
            MateriasLista= _mateService.GetAll().Select(a => 
                                  new SelectListItem 
                                  {
                                      Value = a.Id.ToString(),
                                      Text =  a.Descripcion
                                  }).ToList();

            Profesor = _profService.GetAll().Where(x => x.Legajo == leg).First();
        }

        public IActionResult OnPost()
        {
            /*
            if (profesor.Foto != null)
            {
                string carpetaFotos = Path.Combine(_hostingEnvironment.WebRootPath, "images");
                string nombreArchivo = profesor.Foto.FileName;
                string rutaCompleta = Path.Combine(carpetaFotos, nombreArchivo);
                //subimos la imagen al servidor
                profesor.Foto.CopyTo(new FileStream(rutaCompleta, FileMode.Create));
                //guardar la ruta de la imagen en la base de datos
                profesor.FotoRuta = nombreArchivo;
            }*/
            var materia=_mateService.GetAll().Where(x=>x.Id==Profesor.MateriaDictadaId).First();
            Profesor.MateriaDictada=materia;
            _profService.Modificar(Profesor);
            //var profe2=profesor;
            MensajeExitoso="Se modificó correctamente.";
            return RedirectToPage("Index");
        }
    }
}

Pages/Profesores/Nuevo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProyHerramientas.Pages.Profesores
{
    public class NuevoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Alumnos/Editar.cshtml
@page
@model ProyHerramientas.Pages.EditarModel
@{
}
 
<form method="post"   >
    <div class="form-group row">
        <label  for="id" class="col-sm-2 col-form-label" >Numero Id</label>
    @* <input type="text" name="id" value="" placeholder="ingrese el id" />*@
        <div class="col-sm-10">
            <input asp-for="id" placeholder="ingrese el id" />
        </div> 
    </div>
    <div class="form-group row"> 
        <label for="recibido">Recibido</label>
        @*<input type="checkbox" name="recibido" value="recibidoOk"/>*@
        <input asp-for="recibido"/>
    </div>
    <div class="form-group"> 
        <label for="fechanacimiento">Fecha de Nacimiento</label>
        <input type="date" name="fechanacimiento" />
    </div>
    <div class="form-group"> 
        <label for="clave">Password de Usuario</label>
        @*<input type="password" name="clave"/>*@
        <input asp-for="clave"/>
    </div>
    <div class="form-group"> 
        <label for="opcion">Opción</label>
        <input type="radio" name="opcion" id="matematicas" value="MATE" />
        <label for="matematicas">Matematicas</label>
        <input type="radio" name="opcion" id="programacion" value="PROG" />
        <label for="progamacion">Programacion</label>
    </div>
    <div class="form-group"> 
        <label for="mail">E-mail</label>
        @*<input type="email" name="mail"/>*@
        <input asp-for="mail"/>
    </div>
    <div class="form-group"> 
        <label for="archivo">Foto</label>
        @*<input type="file"  name="archivo"/>*@
        <input asp-for="archivo" />
    </div>
    <div class="form-group">  
        <label for="rango">Rango</label>
        <input type="range" name="rango" /> 
    </div>
    <div class="form-group"> 
        <input type="submit" class="btn btn-success" value="Guardar Alumno"/>
    </div>
</form>

Pages/Alumnos/Nuevo.cshtml
@page
@model ProyHerramientas.Pages.Alumnos.NuevoModel
@{
    var mimensaje= "Hola Mundo";
    //comentario
    var fechaactual= DateTime.Now.DayOfWeek;
    var mensajeyfecha= mimensaje + " " + fechaactual;
}
@* 
comentarios 
*@
<form method="post"  >
    <p>El mensaje es: @mensajeyfecha</p>
    <p>@Model.TotalAlumnos</p>
    <p>@Model.NombreProfesor</p>
    <p><b>@ViewData["instituto"]</b></p>
    <label  for="id" >Numero Id</label>
    <input type="text" name="id"  placeholder="ingrese el id" />
    <label for="recibido">Recibido</label>
    <input type="checkbox" name="recibido" value="recibidoOk"/>
    <label for="fechanacimiento">Fecha de Nacimiento</label>
    <input type="date" name="fechanacimiento" />
    <label for="clave">Password de Usuario</label>
    <input type="password" name="clave"/>
    <label for="opcion">Opción</label>
    <input type="radio" name="opcion" id="matematicas" value="MATE" />
    <label for="matematicas">Matematicas</label>
    <input type="radio" name="opcion" id="programacion" value="PROG" />
    <label for="progamacion">Programacion</label>
    <label for="mail">E-mail</label>
    <input type="email" name="mail"/>
    <label for="archivo">Foto</label>
    <input type="file"  name="archivo"/>
    <label for="rango">Rango</label>
    <input type="range" name="rango" /> 
    
    <input type="submit" class="btn btn-success" value="Guardar Alumno"/>
</form>
<form method="post" asp-page-handler="Modificar">
    <button class="btn btn-default">Guardar otro post</button>
</form>
<form method="post" asp-page-handler="Verificar">
    <button class="btn btn-danger">Verificar</button>
</form>
<a href="/Alumnos/Nuevo" class="btn btn-warning">Utilizar Get</a>