Pages/Alumnos/Editar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations; 

namespace ProyHerramientas.Pages
{
    [BindProperties]
    public class EditarModel : PageModel
    {
        
        public int id {get;set;}
        [DataType("Password")]
        public string clave{get;set;}
        public bool recibido {get;set;}
        [DataType("EmailAddress")]
        public string mail {get;set;}
        public IFormFile archivo {get;set;}
        public void OnGet()
        {
            id=9999;
        }

        public void OnPost(){
            var numeroid=id;
            var pass=clave;
        }
    }
}

Pages/Alumnos/Nuevo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProyHerramientas.Pages.Alumnos
{
    public class NuevoModel : PageModel
    {
        public int TotalAlumnos=20;
        public string NombreProfesor {get;set;}
        public void OnGet()
        {
            ViewData["instituto"]="ISTEA"; 
            NombreProfesor="Laura Alonso";
        }
        public void OnPost(){
            NombreProfesor="Marina Lopez";
            //var formulario=Request.Form; 
            var numeroid= Request.Form["id"];
            var fecha=Request.Form["fechanacimiento"];
            var pass=Request.Form["clave"];
            var recibi=Request.Form["recibido"];
            var opcion=Request.Form["opcion"];
            var mail=Request.Form["mail"];
            var archivo=Request.Form["archivo"];
            var rango=Request.Form["rango"];

        }
        public void OnPostModificar(){
            NombreProfesor="Nicolas Fernandez";
        }

        public IActionResult OnPostVerificar(){
            return Page();
            //return RedirectToPage("Index");
        }
    }
}

Pages/Profesores/Editar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyHerramientas.Models;
using ProyHerramientas.Servicios;

namespace ProyHerramientas.Pages.Profesores
{
    public class EditarModel : PageModel
    {
        [TempData]
        public string MensajeExitoso{get;set;}
        public List<SelectListItem> MateriasLista { get; set; }
        private readonly IProfesorServicio _profService;
        private readonly IMateriaServicio _mateService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public EditarModel(IProfesorServicio profServicio,IMateriaServicio mateServicio, IWebHostEnvironment hostingEnviroment)
        {
            _profService = profServicio;
            _mateService = mateServicio;
            _hostingEnvironment = hostingEnviroment;
        }

        [BindProperty]
        public Profesor Profesor { get; set; }
        public void OnGet(int leg)
        {
            MateriasLista= _mateService.GetAll().Select(a => 
                                  new SelectListItem 
                                  {
                                      Value = a.Id.ToString(),
                                      Text =  a.Descripcion
                                  }).ToList();

            Profesor = _profService.GetAll().Where(x => x.Legajo == leg).First();
        }

        public IActionResult OnPost()
        {
            /*
            if (profesor.Foto != null)
            {
                string carpetaFotos = Path.Combine(_hostingEnvironment.WebRootPath, "images");
                string nombreArchivo = profesor.Foto.FileName;
                string rutaCompleta = Path.Combine(carpetaFotos, nombreArchivo);
                //subimos la imagen al servidor
                profesor.Foto.CopyTo(new FileStream(rutaCompleta, FileMode.Create));
                //guardar la ruta de la imagen en la base de datos
                profesor.FotoRuta = nombreArchivo;
            }*/
            var materia=_mateService.GetAll().Where(x=>x.Id==Profesor.MateriaDictadaId).First();
            Profesor.MateriaDictada=materia;
            _profService.Modificar(Profesor);
            //var profe2=profesor;
            MensajeExitoso="Se modificó correctamente.";
            return RedirectToPage("Index");
        }
    }
}

Pages/Profesores/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProyHerramientas.Models;
using ProyHerramientas.Servicios;

namespace ProyHerramientas.Pages.Profesores
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string MensajeExitoso{get;set;}
        [BindProperty]
        public List<Profesor> Profesores { get; set; }
        private IProfesorServicio _profServicio;
        public string LegajoOrden;
        public string CurrentSort { get; set; }
        public IndexModel(IProfesorServicio profServicio){
                _profServicio = profServicio;            
        } 
        public void OnGet(string CampoOrden,int LegajoFiltro,string ApellidoFiltro)
        {
            CurrentSort = CampoOrden;
            //LegajoOrden = String.IsNullOrEmpty(CampoOrden) ? "Cust_ID" : "";
            LegajoOrden = (CampoOrden == "Legajo_Asc_Sort") ? "Legajo_Desc_Sort" : "Legajo_Asc_Sort";
            Profesores = _profServicio.GetAll().ToList();
            if(LegajoFiltro !=null && LegajoFiltro>0)
                Profesores = Profesores.Where(x => x.Legajo == LegajoFiltro).ToList();
            if (ApellidoFiltro != null && ApellidoFiltro.Length > 0) {
                Profesores = Profesores.Where(x => x.Apellido.ToUpper().Contains(ApellidoFiltro.ToUpper())).ToList();
            }

            switch (CampoOrden)
            {
                case "Cust_ID":
                    Profesores = Profesores.OrderByDescending(s => s.Id).ToList();
                    break;
                case "Legajo_Asc_Sort":
                    Profesores = Profesores.OrderBy(s => s.Legajo).ToList();
                    break;
                case "Legajo_Desc_Sort":
                    Profesores = Profesores.OrderByDescending(s => s.Legajo).ToList();
                    break;
                case "OrdenPorApellidoAsc":
                    Profesores = Profesores.OrderBy(s => s.Apellido).ToList();
                    break;
                case "OrdenPorApellidoDesc":
                    Profesores = Profesores.OrderByDescending(s => s.Apellido).ToList();
                    break;
                default:
                    //cust = cust.OrderBy(s => s.CustomerId);
                    break;
            }
        }

        public void OnGetDelete(int legajoborrar)
        {
            var ProfesorBuscado = _profServicio.GetAll().Where(x => x.Legajo == legajoborrar).First();
            _profServicio.Eliminar(ProfesorBuscado);
            Profesores = _profServicio.GetAll().ToList();
        }

        public void OnPostFiltrar(int LegajoFiltro)
        {
            Profesores = _profServicio.GetAll().Where(x => x.Legajo == LegajoFiltro).ToList();
        }
    }
}

Pages/Profesores/Nuevo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProyHerramientas.Pages.Profesores
{
    public class NuevoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Profesores/Editar.cshtml
 @page
@model ProyHerramientas.Pages.Profesores.EditarModel
 
@{
    var materiascombo = ViewData["Materias"];
}

@if (@Model.Profesor == null || @Model.Profesor.Legajo == 0)
{
    <h2>Ingresar Nuevo Profesor</h2>
}
else
{
    <h2>Modificar profesor legajo : <span>@Model.Profesor.Legajo</span> </h2>
   
    @*  <h2>Modificar profesor legajo : <span>@Model.Legajo</span> </h2>*@
}
<form method="post" class="form-group" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Profesor.Legajo"></label>
        <input  asp-for="Profesor.Legajo" placeholder="Ingresar Legajo" />
        <span asp-validation-for="Profesor.Legajo" class="badge bg-danger"></span>
    </div>
    <div class="form-group">
        <input type="text" asp-for="Profesor.Nombre" placeholder="Ingresar Nombre" />
        <span asp-validation-for="Profesor.Nombre" class="badge bg-danger"></span>
    </div>
    <div class="form-group">
        <input type="text" asp-for="Profesor.Apellido" placeholder="Ingresar Apellido" />
        <span asp-validation-for="Profesor.Apellido" class="badge bg-danger"></span>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input class="form-check-input" type="radio" asp-for="Profesor.EstudioTipo" value="1" checked>
            <label class="form-check-label" for="exampleRadios1">
                Default radio
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" asp-for="Profesor.EstudioTipo" value="2">
            <label class="form-check-label" for="exampleRadios2">
                Second default radio
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" asp-for="Profesor.EstudioTipo" value="3">
            <label class="form-check-label" for="exampleRadios3">
                Disabled radio
            </label>
        </div>
    </div>
    <div class="form-group">
        <input asp-for="Profesor.FechaNacimiento" placeholder="Ingresar Fecha" />
        <span asp-validation-for="Profesor.FechaNacimiento" class="badge badge-danger"></span>
    </div>
    @*
    <div class="form-group" style="@(@Model == null ? "display:none" : "display:block" )">
    <input type="text" asp-for="@Model.Legajo" placeholder="Ingresar Legajo" />
    <span asp-validation-for="Legajo"  class="badge badge-danger"></span>
    </div>
  

    <div class="form-group">
        <input type="text" asp-for="@Model.Nombre" placeholder="Ingresar Nombre" />
        <span asp-validation-for="Nombre" class="badge bg-danger"></span>
    </div>
   
    </div>

    <div class="form-group">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" asp-for="Activo" />
            <label class="form-check-label" for="defaultCheck1">
                ¿Activo?
            </label>
        </div>
    </div>
    *@
    <div class="form-group">
        <div class="form-check">
            @*
            @Html.DropDownList("MateriaDictada_Id", (IEnumerable <SelectListItem>)ViewData["Materias"])
           *@
            <select asp-for="Profesor.MateriaDictadaId"  asp-items="Model.MateriasLista" >
                
            </select>
            
        </div>
    </div>

@*    <div class="form-group">
        @Html.LabelFor(p=>p.Foto)
        <div class="custom-file">
            @Html.TextBoxFor(p=>p.Foto, new {type="file",@class="form-control custom-file-input"})
            @Html.LabelFor(p=>p.Foto,"Seleccionar Foto",new { @class="custom-file-label"})
        </div>
    </div>*@
    <input type="submit" value="Enviar" />
</form>

Pages/Profesores/Index.cshtml
@page
@model ProyHerramientas.Pages.Profesores.IndexModel
@{
}

@functions{
    void MostrarActivo(bool activo){
        if(activo){
            <span>SI</span>;
        }
        else{
            <span>NO</span>;
        }
      
    }
 

    void MostrarFechaNacimiento(DateTime dt){
        <span class="date">@dt.ToString("dd/MM/yyyy")   </span>;
    }
    void MostrarEstudioTipo(int tipo){
        var tipoestudio="";
        if(tipo==1){
            tipoestudio="Secundario";
        }
        else if(tipo==2){
            tipoestudio="Terciario";
        }
        else{
            tipoestudio="Universitario";
        }
        <span>@tipoestudio</span>;
    }
      void MostrarEstudioTipo2(int tipo){
         
        if(tipo==1){
            <span class="badge bg-danger">Secundario</span>;
        }
        else if(tipo==2){
                <span class="badge bg-warning">Terciario</span>;
        }
        else{
                <span class="badge bg-success">Universitario</span>;
        }
         
    }
}
@if(Model.MensajeExitoso!=null){
<div class="alert alert-success alert-dismissible fade show" role="alert">
    @Model.MensajeExitoso
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"/>
</div>
}
<h3>Vista parcial</h3>
@*<form asp-page="Listado" method="post" asp-page-handler="Filtrar">
    <input type="text" name="LegajoFiltro" placeholder="Buscar por legajo" />
    <input type="submit"  class="btn btn-warning"  value="Buscar"/>
</form>*@
<form asp-page="Listado" method="get" >
    <input type="text" name="LegajoFiltro" placeholder="Buscar por legajo" />
    <input type="text" name="ApellidoFiltro" placeholder="Buscar por Apellido" />
    <input type="submit"  class="btn btn-warning"  value="Buscar"/>
</form>
<a asp-page="Nuevo" class="btn btn-success" >Nuevo</a>
 <table class="table">
        <thead>
            <tr>
                <th> 
                    <a asp-page="./Index" asp-route-CampoOrden="@Model.LegajoOrden">
                        @Html.DisplayNameFor(model => model.Profesores[0].Legajo)
                    </a>
                </th>
                <th>
                    <a asp-page="./Index" asp-route-CampoOrden="OrdenPorApellidoAsc">
                        Apellido Asc
                    </a>
                    <a asp-page="./Index" asp-route-CampoOrden="OrdenPorApellidoDesc">
                        Apellido Desc
                    </a>
                </th>
                <th>
                    <a asp-page="./ProfesorList" asp-route-CampoOrden="OrdenPorNombre">
                        Nombre
                    </a>
                    
                </th>
                <th>Fecha nacimiento</th>
                <th>Estudio tipo</th>
                <th>Activo</th>
                <th>Materia</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Profesores)
            {
            <tr>
                <td>@item.Legajo
                    <img asp-append-version="true" src="~/images/imagen.jpg" class="rounded-circl" style="width:75px;height:75px;" />
                    <i class="bi-github" role="img" aria-label="GitHub"></i>
                </td>
                <td>@item.Apellido</td>
                <td>@item.Nombre</td>
                <td>@{MostrarFechaNacimiento(item.FechaNacimiento);}</td>
                <td>@{MostrarEstudioTipo2(item.EstudioTipo);}</td>
                <td>@{MostrarActivo(item.ADistancia);} </td>
                <td>@item.MateriaDictada.Descripcion</td>
                <td>
                    <a asp-page="./Editar" class="btn btn-primary" asp-route-leg="@item.Legajo">Editar</a> | 
                    <a asp-page="Listado"  class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?')" asp-page-handler="delete" asp-route-legajoborrar="@item.Legajo">Borrar con A</a>
                </td>
            </tr> 
            } 
        </tbody>
    </table>

Pages/Profesores/Nuevo.cshtml
@page
@model ProyHerramientas.Pages.Profesores.NuevoModel
@{
}